### ISSUE TITLE
Navdata was already bootstrapped java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by 452** [MahatmaX/YADrone#12]
Hello from Ukraine =)
Ubuntu 13.10 x64
ihor@ihor-M50Vc:~$ java -version
java version "1.7.0_45"
Java(TM) SE Runtime Environment (build 1.7.0_45-b18)
Java HotSpot(TM) 64-Bit Server VM (build 24.45-b08, mixed mode)

```
import de.yadrone.base.ARDrone;
import de.yadrone.base.IARDrone;
import de.yadrone.base.command.LEDAnimation;

public class Main {

public static void main(String[] args) {
    final IARDrone drone = new ARDrone("192.168.1.69");
    try {
        drone.start();
        // drone.takeOff();
        // drone.landing();
        drone.getCommandManager().setLedsAnimation(LEDAnimation.BLINK_GREEN_RED, 3, 10);
        Thread.sleep(20000);
        // drone.getNavDataManager().addBatteryListener(new
        // BatteryListener() {
        // public void batteryLevelChanged(int percentage) {
        // System.out.println("Battery: " + percentage + " %");
        // }
        //
        // public void voltageChanged(int vbat_raw) {
        // }
        // });
        // new TutorialVideoListener(drone);
    } catch (Exception e) {
        e.printStackTrace();
    } finally {
        if (drone != null) {
            drone.reset();
            drone.stop();
        }
        System.exit(-1);
    }
}
}
```

<pre>
CommandManager: setOutdoor(flyingOutdoor,usingOutdoorHull) = false,false
CommandManager: setMaxAltitude: 10000 mm
CommandManager: setMaxVz (verticalSpeed): 1000 mm
CommandManager: setMaxEulerAngle (bendingAngle): 0.25 rad
AbstractManager: Starting CommandManager
AbstractManager: Starting NavDataManager
Navdata was already bootstrapped
java.lang.IllegalArgumentException
    at java.nio.Buffer.limit(Buffer.java:267)
    at de.yadrone.base.navdata.NavDataManager.parse(NavDataManager.java:415)
    at de.yadrone.base.navdata.NavDataManager.run(NavDataManager.java:341)
    at java.lang.Thread.run(Thread.java:744)
java.lang.IllegalArgumentException
    at java.nio.Buffer.limit(Buffer.java:267)
    at de.yadrone.base.navdata.NavDataManager.parse(NavDataManager.java:415)
    at de.yadrone.base.navdata.NavDataManager.run(NavDataManager.java:341)
    at java.lang.Thread.run(Thread.java:744)
java.lang.IllegalArgumentException
    at java.nio.Buffer.limit(Buffer.java:267)
    at de.yadrone.base.navdata.NavDataManager.parse(NavDataManager.java:415)
    at de.yadrone.base.navdata.NavDataManager.run(NavDataManager.java:341)
    at java.lang.Thread.run(Thread.java:744)
java.lang.IllegalArgumentException
    at java.nio.Buffer.limit(Buffer.java:267)
    at de.yadrone.base.navdata.NavDataManager.parse(NavDataManager.java:415)
    at de.yadrone.base.navdata.NavDataManager.run(NavDataManager.java:341)
    at java.lang.Thread.run(Thread.java:744)
java.lang.IllegalArgumentException
    at java.nio.Buffer.limit(Buffer.java:267)
    at de.yadrone.base.navdata.NavDataManager.parse(NavDataManager.java:415)
    at de.yadrone.base.navdata.NavDataManager.run(NavDataManager.java:341)
    at java.lang.Thread.run(Thread.java:744)
java.lang.IllegalArgumentException
    at java.nio.Buffer.limit(Buffer.java:267)
    at de.yadrone.base.navdata.NavDataManager.parse(NavDataManager.java:415)
    at de.yadrone.base.navdata.NavDataManager.run(NavDataManager.java:341)
    at java.lang.Thread.run(Thread.java:744)
java.lang.IllegalArgumentException
    at java.nio.Buffer.limit(Buffer.java:267)
    at de.yadrone.base.navdata.NavDataManager.parse(NavDataManager.java:415)
    at de.yadrone.base.navdata.NavDataManager.run(NavDataManager.java:341)
    at java.lang.Thread.run(Thread.java:744)
Control ack timeout true
java.lang.IllegalArgumentException
    at java.nio.Buffer.limit(Buffer.java:267)
    at de.yadrone.base.navdata.NavDataManager.parse(NavDataManager.java:415)
    at de.yadrone.base.navdata.NavDataManager.run(NavDataManager.java:341)
    at java.lang.Thread.run(Thread.java:744)
java.lang.IllegalArgumentException
    at java.nio.Buffer.limit(Buffer.java:267)
    at de.yadrone.base.navdata.NavDataManager.parse(NavDataManager.java:415)
    at de.yadrone.base.navdata.NavDataManager.run(NavDataManager.java:341)
    at java.lang.Thread.run(Thread.java:744)
java.lang.IllegalArgumentException
    at java.nio.Buffer.limit(Buffer.java:267)
    at de.yadrone.base.navdata.NavDataManager.parse(NavDataManager.java:415)
    at de.yadrone.base.navdata.NavDataManager.run(NavDataManager.java:341)
    at java.lang.Thread.run(Thread.java:744)
AbstractManager: Stopping CommandManager
AbstractManager: Stopping NavDataManager
Stopped NavDataManager
doStop() called ? true ... Stopped CommandManager
Dec 09, 2013 5:59:55 PM com.xuggle.xuggler.io.InputOutputStreamHandler read
SEVERE: Got IO exception reading from stream: java.net.SocketInputStream@468b7aca; java.net.SocketException: Socket closed
</pre>

**Comment by MahatmaX** [comment]
This is actually the same exception as in issue #11 (part 2). The message "Navdata was already bootstrapped" is harmless and should make no worries. The exception possibly related to a new (or an old) firmware version and hence a Navdata parsing error. I will check this soon.
